### ISSUE TITLE
Do you still have the textured square code?

### ISSUE THREAD

**Issue by newdev8** [Jhynjhiruu/sa1#1]
Hello, hope not to bother you but do you still have the code for the [textured square](https://github.com/rust3ds/citro3d-rs/issues/35#issuecomment-1871732945) using Rust? It would really help me as I'm building an app for the 3DS and I completely depend on Rust to do so.
Thanks!

**Comment by Jhynjhiruu** [comment]
I don't have it, no; that got merged and expanded into my [lit textured square including normal map](https://github.com/Jhynjhiruu/lighting) code, which you'll probably find significantly more useful.
As a heads-up, going round to people's other, unrelated repos and asking the exact same question there is likely to result in them being annoyed, rather than helpful. I've been busy over the past few days and I would have responded to your first post fairly soon.

**Comment by newdev8** [comment]
You're right and I'm sorry, I was in a rush to release something soon before I had to go back to work. Thank you and again sorry for the inconvenience!
